fft_setup:
  n_fft: 2048
  win_len: 2048
  hop_length: 1024
  seq_len: 163840
  overlap_ratio: 128
  cut_first: 10240
  sr: 10240
  num_test_samples: 16
  num_blocks: 4

model_param:
  epoch: 1
  device: "cpu"
  batch_size: 1
  lr: 0.001

file_path:
  audio_folder: "../dataset"
  log_dir: "./train_log/"
