fft_setup:
  n_fft: 1024
  win_len: 1024
  hop_length: 512
  seq_len: 163840
  overlap_ratio: 128
  cut_first: 10240
  sr: 10240
  num_test_samples: 64
  num_blocks: 12

model_param:
  epoch: 300
  device: "cuda:0"
  batch_size: 16
  lr: 0.001

file_path:
  audio_folder: "../dataset"
  log_dir: "./train_log/"
