fft:
  n_fft: 512
  win_len: 512
  hop_length: 256
  seq_len: 160000
  overlap_ratio: 4
  cut_first: 4000
  sr: 8000
  num_blocks: 12
  activation_fn: "xATLU"
  norm_fn: "RMSNorm"
  dropout: 0.2
  num_evaluation: 16
model:
  epoch: 1000
  device: "cuda:0"
  batch_size: 64
  lr: 0.0003
  warmup_period: 4000,
  num_workers: 14
  evaluation_cycle: 15
  sampling_steps: 100
  num_samples: 4
file:
  audio_folder: "../dataset"
  log_dir: "./train_log/"
