fft_setup:
  n_fft: 1000
  win_len: 1000
  hop_length: 500
  seq_len: 80000
  overlap_ratio: 16
  cut_first: 8000
  sr: 8000
  num_test_samples: 64
  num_blocks: 4

model_param:
  epoch: 50
  device: "cuda:0"
  batch_size: 128
  lr: 0.001

file_path:
  audio_folder: "../dataset"
  log_dir: "./train_log/"
