fft_setup:
  n_fft: 2048
  win_len: 2048
  hop_length: 1024
  seq_len: 327680
  overlap_ratio: 256
  cut_first: 10240
  sr: 10240
  num_test_samples: 4
  num_blocks: 12

model_param:
  epoch: 10000
  device: "cuda:0"
  batch_size: 16
  lr: 0.0003

file_path:
  audio_folder: "../dataset"
  log_dir: "./train_log/"
