fft:
  n_fft: 512
  win_len: 512
  hop_length: 256
  seq_len: 128000
  overlap_ratio: 8
  cut_first: 4000
  sr: 8000
  num_blocks: 60
  activation_fn: "xATLU"
  norm_fn: "RMSNorm"
  dropout: 0.2
  num_evaluation: 16
model:
  epoch: 1000
  device: "cuda:0"
  batch_size: 1
  lr: 0.00008
  warmup_period: 4000
  num_workers: 14
  evaluation_cycle: 2
  sampling_steps: [50, 100, 200, 500, 1000]
  num_samples: 5
file:
  audio_folder: "../dataset"
  log_dir: "./train_log/"
