fft_setup:
  n_fft: 512
  win_len: 512
  hop_length: 256
  seq_len: 160000
  overlap_ratio: 4
  cut_first: 4000
  sr: 8000
  num_test_samples: 8
  num_blocks: 12
  activation_fn: "xATLU"
  norm_fn: "RMSNorm"
  dropout: 0.2
model_param:
  epoch: 1000
  device: "cuda:0"
  batch_size: 256
  lr: 0.0003

file_path:
  audio_folder: "../dataset"
  log_dir: "./train_log/"
