wandb_version: 1

Device:
  desc: null
  value: No GPU Detected.
fft:
  desc: null
  value:
    n_fft: 512
    win_len: 512
    hop_length: 256
    seq_len: 262144
    overlap_ratio: 1
    cut_first: 4000
    sr: 16000
    num_blocks: 2
    activation_fn: snake
    norm_fn: LayerNorm
    dropout: 0.1
    num_evaluation: 8
    downsampling_ratio: 2048
    num_heads: 8
    embed_dim: 1024
model:
  desc: null
  value:
    epoch: 1000
    batch_size: 24
    lr: 8.0e-05
    warmup_period: 4000
    num_workers: 56
    evaluation_cycle: 250
    num_samples: 8
    pretrained_autoencoder: ../models/pretrained_autoencoder/last.pth
    freeze_encoder: true
    freeze_decoder: true
    resume_diffusion: false
    resume_diffusion_path: ''
    train_precompute: true
    use_precompute: ../preencoded_dataset/
file:
  desc: null
  value:
    audio_folder: ../dataset
    log_dir: ../train_log/
    project_name: DiT
    run_name: 0117-DiT
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1737219213.156996
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.15.4
      8:
      - 2
      - 4
      - 5
