wandb_version: 1

device:
  desc: null
  value: No GPU available.
fft_setup:
  desc: null
  value:
    n_fft: 2048
    win_len: 2048
    hop_length: 1024
    seq_len: 163840
    overlap_ratio: 128
    cut_first: 10240
    sr: 10240
    num_test_samples: 16
    num_blocks: 4
model_param:
  desc: null
  value:
    epoch: 1
    device: cpu
    batch_size: 1
    lr: 0.001
file_path:
  desc: null
  value:
    audio_folder: ../dataset
    log_dir: ./train_log/
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1730353883
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 55
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.17.8
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
